import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '../../constants/theme';

const TILE_GAP = 12;

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg },
  flex: { flex: 1 },
  head: { paddingHorizontal: Spacing.lg, paddingTop: Spacing.sm, height: 48 },
  back: {
    width: 38,
    height: 38,
    borderRadius: Radius.pill,
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  body: {
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.xl,
  },
  previewWrap: { alignItems: 'center', marginBottom: Spacing.md },
  previewAvatar: {
    width: 96,
    height: 96,
    borderRadius: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewEmoji: { fontSize: 48 },
  title: {
    color: Colors.text,
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: -0.4,
    textAlign: 'center',
  },
  sub: {
    color: Colors.textDim,
    fontSize: 13,
    textAlign: 'center',
    marginTop: 4,
    marginBottom: Spacing.lg,
  },
  fieldLabel: {
    color: Colors.textDim,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.6,
    marginBottom: 8,
  },
  field: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderWidth: 1,
    borderRadius: Radius.xl,
    paddingHorizontal: Spacing.md,
    paddingVertical: 14,
  },
  input: { flex: 1, color: Colors.text, fontSize: 15 },
  avatarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: TILE_GAP,
    justifyContent: 'space-between',
  },
  tileWrap: { width: `${(100 - 3) / 4}%`, alignItems: 'center', gap: 6 },
  tile: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: Radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  tileEmoji: { fontSize: 28 },
  checkBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: Colors.bg,
  },
  tileLabel: {
    color: Colors.textDim,
    fontSize: 11,
    fontWeight: '600',
  },
  error: {
    color: '#FF7A6E',
    fontSize: 13,
    fontWeight: '600',
    marginTop: Spacing.md,
  },
  btn: {
    paddingVertical: 14,
    borderRadius: Radius.pill,
    alignItems: 'center',
    marginTop: Spacing.lg,
  },
  btnText: { color: '#131313', fontSize: 15, fontWeight: '800' },
  helpLink: { alignItems: 'center', paddingVertical: 12 },
  helpText: { color: Colors.textDim, fontSize: 12, fontWeight: '600' },
});
