import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '../../constants/theme';

export const SIDE = Spacing.lg;

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    justifyContent: 'space-between',
  },
  title: {
    flex: 1,
    color: Colors.text,
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    shadowOpacity: 0.9,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
  },
  subtitle: {
    color: Colors.textDim,
    fontSize: 12,
    fontWeight: '600',
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.sm,
  },
  list: { paddingHorizontal: SIDE, paddingBottom: 120 },
  headerWrap: { paddingBottom: Spacing.md },
  card: {
    borderRadius: Radius.lg,
    overflow: 'hidden',
    backgroundColor: Colors.surface,
    borderWidth: 1,
    // Soft accent glow — premium feel.
    shadowOpacity: 0.55,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  cardBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: Radius.pill,
  },
  cardBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#131313',
    letterSpacing: 0.3,
  },
  cardFooter: { position: 'absolute', left: 10, right: 10, bottom: 10 },
  cardTitle: { color: '#fff', fontSize: 14, fontWeight: '800', letterSpacing: -0.2 },
  cardHint: {
    color: 'rgba(255,255,255,0.78)',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 1,
  },
  banner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    padding: Spacing.md,
    borderRadius: Radius.lg,
    borderWidth: 1,
    backgroundColor: Colors.surface,
  },
  bannerIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bannerTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  bannerTitle: { fontSize: 14, fontWeight: '800', letterSpacing: -0.2 },
  bannerBody: { color: Colors.textDim, fontSize: 12, fontWeight: '600', marginTop: 2 },
  lockedWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Spacing.xl,
    gap: Spacing.md,
  },
  lockedGlyph: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Spacing.sm,
  },
  lockedTitle: {
    color: Colors.text,
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: -0.4,
    textAlign: 'center',
  },
  lockedSub: {
    color: Colors.textDim,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    marginBottom: Spacing.md,
  },
  lockedBtn: {
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: Radius.pill,
    alignItems: 'center',
  },
  lockedBtnText: { color: '#131313', fontSize: 15, fontWeight: '800' },
});
