import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '../../constants/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    justifyContent: 'space-between',
  },
  backBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: -0.3,
    flex: 1,
    textAlign: 'center',
  },
  body: { paddingHorizontal: Spacing.lg, paddingBottom: 40, gap: Spacing.lg },
  hero: {
    borderRadius: Radius.lg,
    overflow: 'hidden',
    borderWidth: 1,
    backgroundColor: Colors.surface,
    shadowOpacity: 0.5,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  heroPill: {
    position: 'absolute',
    top: 12,
    left: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: Radius.pill,
  },
  heroPillText: { fontSize: 11, fontWeight: '800', color: '#131313', letterSpacing: 0.3 },
  heroFooter: { position: 'absolute', left: 14, right: 14, bottom: 14 },
  heroTitle: { color: '#fff', fontSize: 18, fontWeight: '900', letterSpacing: -0.3 },
  heroSub: { color: 'rgba(255,255,255,0.8)', fontSize: 12, lineHeight: 17, marginTop: 3 },
  sectionHead: { gap: 4 },
  sectionTitle: { fontSize: 16, fontWeight: '800', letterSpacing: -0.2 },
  sectionSub: { color: Colors.textDim, fontSize: 12, lineHeight: 17 },
  soloRow: { flexDirection: 'row', gap: Spacing.md },
  soloCard: {
    borderRadius: Radius.lg,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
  },
  check: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  soloFooter: { position: 'absolute', left: 10, right: 10, bottom: 10 },
  soloLabel: { color: '#fff', fontSize: 15, fontWeight: '800' },
  soloHint: { color: 'rgba(255,255,255,0.78)', fontSize: 11, fontWeight: '600', marginTop: 1 },
  statusWrap: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  statusDot: { width: 10, height: 10, borderRadius: 5 },
  statusText: { fontSize: 13 },
  cta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 15,
    borderRadius: Radius.pill,
  },
  ctaText: { fontSize: 15, fontWeight: '800', color: '#131313' },
  footnote: {
    color: Colors.textDim,
    fontSize: 11,
    lineHeight: 16,
    textAlign: 'center',
    paddingHorizontal: Spacing.md,
  },
});
