import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '../../constants/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.sm,
    paddingBottom: Spacing.md,
    gap: Spacing.md,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: Radius.pill,
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: { fontSize: 18, fontWeight: '800', letterSpacing: -0.3 },
  subtitle: {
    color: Colors.textDim,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  list: { paddingHorizontal: Spacing.lg, paddingBottom: 140 },
  empty: {
    color: Colors.textDim,
    textAlign: 'center',
    marginTop: 60,
    fontSize: 13,
    fontWeight: '600',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    padding: Spacing.sm,
    borderRadius: Radius.lg,
    backgroundColor: Colors.surface,
    borderWidth: 1.5,
    borderColor: Colors.border,
    shadowOpacity: 0.45,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
  },
  thumbWrap: {
    width: 64,
    height: 80,
    borderRadius: Radius.md,
    overflow: 'hidden',
    backgroundColor: Colors.surfaceHi,
  },
  thumbFade: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: '60%',
  },
  kindPill: {
    position: 'absolute',
    top: 5,
    left: 5,
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: Radius.pill,
  },
  kindPillText: {
    fontSize: 8,
    fontWeight: '900',
    color: '#131313',
    letterSpacing: 0.5,
  },
  body: { flex: 1, gap: 4 },
  name: { fontSize: 14, fontWeight: '800', letterSpacing: -0.2 },
  meta: { color: Colors.textDim, fontSize: 11, fontWeight: '700' },
  tallyRow: { flexDirection: 'row', gap: 4, marginTop: 4 },
  tallyCell: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  tallyEmoji: { fontSize: 11 },
  tallyCount: { fontSize: 10, fontWeight: '800' },
  createRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    padding: Spacing.sm,
    borderRadius: Radius.lg,
    backgroundColor: Colors.surface,
    borderWidth: 1.5,
    borderStyle: 'dashed',
  },
  createIcon: {
    width: 64,
    height: 80,
    borderRadius: Radius.md,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  createTitle: { fontSize: 14, fontWeight: '800', letterSpacing: -0.2 },
  createCaption: {
    color: Colors.textDim,
    fontSize: 11,
    fontWeight: '700',
    marginTop: 4,
  },
  errorWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Spacing.lg,
    gap: 12,
  },
  errorTitle: {
    color: Colors.text,
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: -0.3,
    textAlign: 'center',
  },
  errorMsg: {
    color: Colors.textDim,
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 8,
  },
  errorBtn: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: Radius.pill,
    borderWidth: 1.5,
  },
  errorBtnText: { fontSize: 13, fontWeight: '800', letterSpacing: 0.3 },
});
