import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '../../constants/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    justifyContent: 'space-between',
  },
  backBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: -0.3,
    flex: 1,
    textAlign: 'center',
  },
  card: {
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.md,
    padding: Spacing.md,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    gap: Spacing.sm,
  },
  partnerRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  partnerName: { fontSize: 16, fontWeight: '800', letterSpacing: -0.2 },
  partnerRoleEmoji: { fontSize: 14 },
  partnerSub: { color: Colors.textDim, fontSize: 11, fontWeight: '600', marginTop: 2 },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: Radius.pill,
    borderWidth: 1,
  },
  statusDot: { width: 6, height: 6, borderRadius: 3 },
  statusPillText: { fontSize: 11, fontWeight: '800', letterSpacing: 0.4 },
  distanceRow: { paddingTop: Spacing.xs },
  distanceBig: { fontSize: 36, fontWeight: '900', letterSpacing: -1 },
  distanceSub: { color: Colors.textDim, fontSize: 12, fontWeight: '600' },
  banner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: Radius.md,
    backgroundColor: 'rgba(232,194,117,0.08)',
  },
  bannerText: { fontSize: 12, fontWeight: '700' },
  cardHeadRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
  },
  cardTitle: { fontSize: 14, fontWeight: '800', letterSpacing: -0.2 },
  cardSubtle: { color: Colors.textDim, fontSize: 11, fontWeight: '600' },
  activeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    padding: Spacing.sm,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  activeThumb: { width: 64, height: 80, borderRadius: Radius.sm },
  activeTitle: { fontSize: 14, fontWeight: '800' },
  activeSub: { color: Colors.textDim, fontSize: 11, fontWeight: '600' },
  activeEmpty: { justifyContent: 'flex-start', backgroundColor: Colors.bgAlt },
  activeEmptyText: { color: Colors.textDim, fontSize: 12, flex: 1 },
  previewIconBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  packGrid: { gap: Spacing.sm },
  packTile: {
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.bgAlt,
    overflow: 'hidden',
  },
  packTileTriptych: { flexDirection: 'row', height: 88 },
  packTileSolo: { flex: 1, height: '100%' },
  packTileTogether: {
    flex: 1.4,
    height: '100%',
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: Colors.border,
  },
  packTileMeta: { paddingHorizontal: 10, paddingVertical: 8, gap: 2 },
  packTileName: { fontSize: 13, fontWeight: '800', letterSpacing: -0.2 },
  packTileBlurb: { fontSize: 10, color: Colors.textDim },
  selectedDot: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  controlsRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.lg,
    marginBottom: Spacing.md,
  },
  ctrlBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    borderRadius: Radius.pill,
  },
  ctrlBtnText: { fontSize: 13, fontWeight: '800' },
  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: Radius.pill,
  },
  primaryBtnText: { fontSize: 15, fontWeight: '800', color: '#131313' },
  privacyText: {
    fontSize: 11,
    color: Colors.textDim,
    lineHeight: 18,
    textAlign: 'center',
    paddingHorizontal: Spacing.lg,
  },
  errText: {
    color: '#ff6b6b',
    fontSize: 12,
    paddingHorizontal: Spacing.lg,
    marginTop: Spacing.sm,
  },
  emptyWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: Spacing.md },
  emptyTitle: { fontSize: 18, fontWeight: '800' },
});
