import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '../../constants/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    justifyContent: 'space-between',
  },
  backBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: { fontSize: 18, fontWeight: '800', letterSpacing: -0.3, flex: 1, textAlign: 'center' },
  body: { paddingHorizontal: Spacing.lg, gap: Spacing.md, paddingBottom: 40 },
  restoreBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    padding: Spacing.md,
    borderRadius: Radius.lg,
    borderWidth: 1,
    backgroundColor: Colors.surface,
  },
  restoreTitle: { fontSize: 14, fontWeight: '800', letterSpacing: -0.2 },
  restoreSub: { color: Colors.textDim, fontSize: 11, lineHeight: 15, marginTop: 2 },
  card: {
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    padding: Spacing.md,
    gap: Spacing.md,
  },
  cardHead: { flexDirection: 'row', gap: Spacing.sm, alignItems: 'flex-start' },
  cardIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTitle: { fontSize: 15, fontWeight: '800', letterSpacing: -0.2 },
  cardBody: { color: Colors.textDim, fontSize: 12, lineHeight: 18, marginTop: 2 },
  sectionLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: Colors.textDim,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  sectionSubLabel: {
    fontSize: 11,
    color: Colors.textDim,
    lineHeight: 16,
    marginTop: -8,
  },
  packRow: { gap: Spacing.sm, paddingVertical: 4 },
  packCard: {
    width: 160,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.bgAlt,
    padding: 8,
    gap: 6,
  },
  packTriptych: {
    flexDirection: 'row',
    height: 90,
    borderRadius: Radius.sm,
    overflow: 'hidden',
    backgroundColor: Colors.bg,
  },
  packSolo: { flex: 1, height: '100%' },
  packTogether: { flex: 1.4, height: '100%', borderLeftWidth: 1, borderRightWidth: 1, borderColor: Colors.border },
  packName: { fontSize: 13, fontWeight: '800', letterSpacing: -0.2 },
  packBlurb: { fontSize: 10, color: Colors.textDim, lineHeight: 14 },
  roleRow: { flexDirection: 'row', gap: Spacing.sm },
  roleCard: {
    flex: 1,
    height: 140,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: 'hidden',
  },
  roleOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    padding: 8,
    backgroundColor: 'rgba(19,19,19,0.75)',
    alignItems: 'center',
  },
  roleEmoji: { fontSize: 18 },
  roleLabel: { color: '#fff', fontSize: 13, fontWeight: '800' },
  roleSub: { color: 'rgba(255,255,255,0.7)', fontSize: 10, marginTop: 2 },
  codeWrap: { gap: Spacing.sm, alignItems: 'center' },
  codeText: {
    fontSize: 34,
    fontWeight: '900',
    letterSpacing: 4,
    fontVariant: ['tabular-nums'],
  },
  codeMeta: { color: Colors.textDim, fontSize: 12, fontWeight: '700' },
  codeBtnRow: { flexDirection: 'row', gap: Spacing.sm },
  smallBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: Radius.pill,
    borderWidth: 1,
  },
  smallBtnText: { fontSize: 12, fontWeight: '700' },
  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: Radius.pill,
  },
  primaryBtnText: { fontSize: 15, fontWeight: '800', color: '#131313' },
  orRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  orLine: { flex: 1, height: 1, backgroundColor: Colors.border },
  orText: { color: Colors.textDim, fontSize: 12, fontWeight: '700' },
  input: {
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.bgAlt,
    paddingHorizontal: Spacing.md,
  },
  inputText: {
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 3,
    paddingVertical: 14,
    textAlign: 'center',
  },
  acceptRoleRow: { flexDirection: 'row', gap: Spacing.xs },
  acceptRoleChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingVertical: 10,
    borderRadius: Radius.pill,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  acceptRoleEmoji: { fontSize: 14 },
  acceptRoleLabel: { fontSize: 12, fontWeight: '800' },
  privacyText: {
    fontSize: 11,
    color: Colors.textDim,
    lineHeight: 18,
    textAlign: 'center',
    paddingHorizontal: Spacing.md,
  },
});
