import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '../../constants/theme';
import { PICKER_GAP } from './constants';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg },
  notFound: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: Spacing.md },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.sm,
    paddingBottom: Spacing.md,
    gap: Spacing.md,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: Radius.pill,
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    flex: 1,
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  scroll: {
    paddingHorizontal: Spacing.lg,
    paddingBottom: 140,
    gap: Spacing.lg,
  },
  card: {
    padding: Spacing.md,
    borderRadius: Radius.lg,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    gap: Spacing.sm,
  },
  cardHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.sm,
  },
  cardLabel: {
    color: Colors.textDim,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  helperText: { color: Colors.textDim, fontSize: 12, fontWeight: '600' },
  input: {
    fontSize: 15,
    fontWeight: '600',
    paddingVertical: 4,
    color: Colors.text,
  },
  numberInput: {
    borderRadius: Radius.sm,
    backgroundColor: Colors.surfaceHi,
    paddingHorizontal: Spacing.md,
    paddingVertical: 8,
    fontSize: 14,
    fontWeight: '700',
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: PICKER_GAP,
    paddingTop: Spacing.xs,
  },
  sourceRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
    paddingTop: Spacing.xs,
  },
  sourceBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 10,
    borderRadius: Radius.md,
    borderWidth: 1.5,
  },
  sourceBtnText: { fontSize: 13, fontWeight: '800', letterSpacing: 0.2 },
  sourceHint: {
    color: Colors.textDim,
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 2,
  },
  urlInput: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    backgroundColor: Colors.surfaceHi,
    paddingHorizontal: Spacing.md,
    paddingVertical: 10,
    fontSize: 14,
    fontWeight: '600',
  },
  urlSaveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    borderRadius: Radius.pill,
  },
  urlSaveBtnText: {
    color: '#131313',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  urlFootnote: {
    color: Colors.textDim,
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 16,
  },
  cell: {
    borderRadius: Radius.md,
    overflow: 'hidden',
    backgroundColor: Colors.surfaceHi,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  cellImg: { width: '100%', height: '100%' },
  cellSelectedFill: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(250,179,202,0.18)',
  },
  selectBadge: {
    position: 'absolute',
    top: 6,
    right: 6,
    minWidth: 24,
    height: 24,
    borderRadius: 12,
    paddingHorizontal: 6,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.5,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
  },
  selectBadgeText: {
    color: '#131313',
    fontSize: 12,
    fontWeight: '900',
  },
  unselectedBadge: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
  },
  countChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: Radius.pill,
    borderWidth: 1,
  },
  countChipText: { fontSize: 12, fontWeight: '800', letterSpacing: 0.3 },
  clearBtn: {
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  clearBtnText: {
    color: Colors.textDim,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.3,
    textDecorationLine: 'underline',
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: 12,
    borderRadius: Radius.md,
    backgroundColor: Colors.surfaceHi,
    borderWidth: 1.5,
    borderColor: Colors.border,
  },
  optionLabel: { color: Colors.text, fontSize: 14, fontWeight: '700' },
  optionCaption: { color: Colors.textDim, fontSize: 11, fontWeight: '600', marginTop: 1 },
  customRow: {
    paddingHorizontal: Spacing.md,
    paddingVertical: 8,
    gap: 6,
  },
  dayNoteRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.md,
    paddingVertical: 12,
    borderRadius: Radius.md,
    backgroundColor: Colors.surfaceHi,
    borderWidth: 1.5,
    borderColor: Colors.border,
  },
  dayNoteText: {
    flex: 1,
    color: Colors.textDim,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 17,
  },
  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: Radius.pill,
    marginTop: Spacing.sm,
  },
  primaryBtnText: {
    color: '#131313',
    fontSize: 14,
    fontWeight: '800',
  },
});
